### PR TITLE
Add legacy born digital and digitization fixtures, update schemas

### LINKED ISSUE #1: Add valid and invalid fixtures for digitization bags
## Is your feature request related to a problem? Please describe.
In order to ensure that JSON files describing bags of digitized records are correctly validated, we need to add fixtures which represent valid and invalid instances.

## Describe the solution you'd like
Add one or more JSON files to a `digitization_bag` subdirectory in both the `valid` and `invalid` directories of the `fixtures` directory. So,
```
/rac_schemas/fixtures/valid/digitization_bag
/rac_schemas/fixtures/invalid/digitization_bag
```

Some things to test:
- the presence (or absence) of required fields
- valid (or invalid) controlled terms

### LINKED ISSUE #2: Add valid and invalid fixtures for legacy digital bags
## Is your feature request related to a problem? Please describe.
In order to ensure that JSON files describing bags of legacy digital records are correctly validated, we need to add fixtures which represent valid and invalid instances.

## Describe the solution you'd like
Add one or more JSON files to a `legacy_digital_bag` subdirectory in both the `valid` and `invalid` directories of the `fixtures` directory. So,
```
/rac_schemas/fixtures/valid/legacy_digital_bag
/rac_schemas/fixtures/invalid/legacy_digital_bag
```

Some things to test:
- the presence (or absence) of required fields
- valid (or invalid) controlled terms

### PR DESCRIPTION
**Pull request by bonniegee**
Adds valid and invalid fixtures for legacy born digital and digitization bags after they've come through Zorya. Will need to be modified after rights statement service is completed. 

Additionally, corrects legacy_digital_bag.json, which had included the schema for accessions, and updates the rights portion of legacy_digital_bag and digitization_bag to refer to base.json.

Fixes #1, fixes #2

### CODE REVIEW

**Comment by helrond** [comment]
@bonniegee It looks like validation is failing on one of the newly-added fixtures.

**Comment by bonniegee** [comment]
I _think_ the issue is the name of one of the fields in the rights statement schema - `begin` vs `start_date`. In the aurora_bag_schema, it's [referred to as the start date](https://github.com/RockefellerArchiveCenter/rac_schemas/blob/master/rac_schemas/schemas/aurora_bag.json#L146); in base.json, which is referred to in the legacy_digital and digitized schemas, it's [referred to as begin](https://github.com/RockefellerArchiveCenter/rac_schemas/blob/master/rac_schemas/schemas/base.json#L449).

I (lazily) copied the rights information from an aurora_bag, which is successfully validated against the aurora_bag_schema.

Does this diagnosis sound correct?

**Comment by helrond** [comment]
@bonniegee I think I actually might have pointed you in the wrong direction yesterday. The rights statement definition in `base.json` refers to rights as they are structured _after_ transformation in Pisces. Your previous approach was headed in the right direction. However, since the structure of these rights statements is (or should be) consistent between bags coming from Aurora and Zorya, I'd still suggest abstracting rights statement out as a separate definition.

**Comment by bonniegee** [comment]
That makes sense. Just to clarify--I should create a rights_statements.json file to refer to?

**Comment by helrond** [comment]
No, just create another definition in `base.json` called something other than `rightsStatement` (like maybe `sourceRightsStatement`) and point to that definition.

**Review by helrond — APPROVED** [review]
Looks good!

**Pull request merged**
